In [3]:
from google.colab import files
uploaded = files.upload()

Saving 20260512_FintechTrainee_CaseStudy_Dataset_FinSightLanka_F.xlsx to 20260512_FintechTrainee_CaseStudy_Dataset_FinSightLanka_F.xlsx

Finsight Analytics Assessment

Data Cleaning & Exploratory Analysis

In [4]:
# import  libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Display settings
pd.set_option('display.max_columns', None)

print("Libraries loaded successfully")

Libraries loaded successfully

In [6]:
# Load Dataset
df = pd.read_excel("20260512_FintechTrainee_CaseStudy_Dataset_FinSightLanka_F.xlsx")
# Display first 5 rows
df.head()

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
0,FSL-0001,Mark Johnson,808614657V,Female,1980-12-26,43,Kandy,Central,Suburban,Regular,2021-02-11,2.9,87812.29,3979.24,1264.91,2714.33,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-07-21,28,Branch,Yes,Verified,2020-01-14,No,No,No,NaN,No,Yes,2,Referral,Friend,Responded,Yes
1,FSL-0002,Deborah Phillips,718478527V,Female,1971-12-13,52,Badulla,Uva,Urban,Starter,2015-11-19,8.1,85045.89,5933.17,3981.82,1951.35,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,0,Branch,No,Expired,2021-04-21,No,No,No,NaN,No,Yes,2,Referral,Family,Ignored,No
2,FSL-0003,Charles Phillips,933515010V,Male,1993-12-17,30,Kandy,Central,Suburban,Regular,2022-03-06,1.8,556766.33,18471.79,9135.59,9336.20,Inactive,Silver,Yes,Personal,2424885.11,48.0,55570.28,On-Time,2022-10-08,2124601.17,Yes,2023-12-01,22,Branch,No,Verified,2023-08-09,No,No,Yes,1166599.45,No,No,3,Agent,Colleague,Responded,No
3,FSL-0004,Rachel Hall,720422796V,Male,1972-02-11,51,Kandy,Central,Suburban,Regular,2019-09-26,4.3,485199.04,20905.30,13745.93,7159.37,Active,Silver,Yes,Personal,2056836.06,12.0,188543.31,Delayed,2022-09-29,1518451.26,No,NaT,2,App,Yes,Verified,2020-01-07,No,No,Yes,1051113.61,Yes,No,4,Referral,NaN,Ignored,Yes
4,FSL-0005,Sharon Bell,940729689V,Male,1994-03-13,29,Colombo,Western,Suburban,Regular,2016-04-03,7.8,744696.92,54156.83,43271.27,10885.56,Active,Silver,Yes,Personal,302677.68,48.0,6936.36,Delayed,2022-03-24,227298.61,Yes,2023-09-30,12,Online,Yes,Verified,2021-03-09,No,No,No,NaN,No,Yes,3,Referral,NaN,Unsubscribed,No

In [7]:
# Load Dataset
df = pd.read_excel("20260512_FintechTrainee_CaseStudy_Dataset_FinSightLanka_F.xlsx")
# Display first 5 rows
df.head()

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
0,FSL-0001,Mark Johnson,808614657V,Female,1980-12-26,43,Kandy,Central,Suburban,Regular,2021-02-11,2.9,87812.29,3979.24,1264.91,2714.33,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-07-21,28,Branch,Yes,Verified,2020-01-14,No,No,No,NaN,No,Yes,2,Referral,Friend,Responded,Yes
1,FSL-0002,Deborah Phillips,718478527V,Female,1971-12-13,52,Badulla,Uva,Urban,Starter,2015-11-19,8.1,85045.89,5933.17,3981.82,1951.35,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,0,Branch,No,Expired,2021-04-21,No,No,No,NaN,No,Yes,2,Referral,Family,Ignored,No
2,FSL-0003,Charles Phillips,933515010V,Male,1993-12-17,30,Kandy,Central,Suburban,Regular,2022-03-06,1.8,556766.33,18471.79,9135.59,9336.20,Inactive,Silver,Yes,Personal,2424885.11,48.0,55570.28,On-Time,2022-10-08,2124601.17,Yes,2023-12-01,22,Branch,No,Verified,2023-08-09,No,No,Yes,1166599.45,No,No,3,Agent,Colleague,Responded,No
3,FSL-0004,Rachel Hall,720422796V,Male,1972-02-11,51,Kandy,Central,Suburban,Regular,2019-09-26,4.3,485199.04,20905.30,13745.93,7159.37,Active,Silver,Yes,Personal,2056836.06,12.0,188543.31,Delayed,2022-09-29,1518451.26,No,NaT,2,App,Yes,Verified,2020-01-07,No,No,Yes,1051113.61,Yes,No,4,Referral,NaN,Ignored,Yes
4,FSL-0005,Sharon Bell,940729689V,Male,1994-03-13,29,Colombo,Western,Suburban,Regular,2016-04-03,7.8,744696.92,54156.83,43271.27,10885.56,Active,Silver,Yes,Personal,302677.68,48.0,6936.36,Delayed,2022-03-24,227298.61,Yes,2023-09-30,12,Online,Yes,Verified,2021-03-09,No,No,No,NaN,No,Yes,3,Referral,NaN,Unsubscribed,No

In [8]:
# Dataset shape
print("Rows and Columns:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Data types
print("\nData Types:")
print(df.dtypes)

Rows and Columns: (508, 44)

Columns:
Index(['Customer_ID', 'Full_Name', 'NIC_Number', 'Gender', 'Date_of_Birth',
       'Age', 'District', 'Province', 'Urban_Rural', 'Customer_Segment',
       'Account_Open_Date', 'Customer_Tenure_Years', 'Savings_Balance',
       'Monthly_Deposit_Avg', 'Monthly_Withdrawal_Avg', 'Net_Monthly_Flow',
       'Account_Status', 'Interest_Rate_Tier', 'Has_Loan', 'Loan_Type',
       'Loan_Amount', 'Loan_Tenure_Months', 'Monthly_Repayment_Amount',
       'Loan_Repayment_Status', 'Loan_Start_Date', 'Outstanding_Loan_Balance',
       'Mobile_App_User', 'Last_Login_Date', 'Monthly_Transaction_Count',
       'Preferred_Channel', 'Push_Notification_Enabled', 'KYC_Status',
       'KYC_Last_Updated', 'Suspicious_Activity_Flag', 'PEP_Flag',
       'Has_Fixed_Deposit', 'FD_Amount', 'Has_Insurance', 'Has_Mobile_Wallet',
       'Number_of_Products', 'Acquisition_Channel', 'Referral_Source',
       'Last_Campaign_Response', 'Promo_Code_Used'],
      dtype='object')

Data Types:
Customer_ID                          object
Full_Name                            object
NIC_Number                           object
Gender                               object
Date_of_Birth                datetime64[ns]
Age                                   int64
District                             object
Province                             object
Urban_Rural                          object
Customer_Segment                     object
Account_Open_Date            datetime64[ns]
Customer_Tenure_Years               float64
Savings_Balance                     float64
Monthly_Deposit_Avg                 float64
Monthly_Withdrawal_Avg              float64
Net_Monthly_Flow                    float64
Account_Status                       object
Interest_Rate_Tier                   object
Has_Loan                             object
Loan_Type                            object
Loan_Amount                         float64
Loan_Tenure_Months                  float64
Monthly_Repayment_Amount            float64
Loan_Repayment_Status                object
Loan_Start_Date              datetime64[ns]
Outstanding_Loan_Balance            float64
Mobile_App_User                      object
Last_Login_Date              datetime64[ns]
Monthly_Transaction_Count             int64
Preferred_Channel                    object
Push_Notification_Enabled            object
KYC_Status                           object
KYC_Last_Updated             datetime64[ns]
Suspicious_Activity_Flag             object
PEP_Flag                             object
Has_Fixed_Deposit                    object
FD_Amount                           float64
Has_Insurance                        object
Has_Mobile_Wallet                    object
Number_of_Products                    int64
Acquisition_Channel                  object
Referral_Source                      object
Last_Campaign_Response               object
Promo_Code_Used                      object
dtype: object

In [9]:
# Missing Value
missing_values = df.isnull().sum()

# Display missing values
missing_values[missing_values > 0].sort_values(ascending=False)

FD_Amount                   358
Loan_Amount                 291
Monthly_Repayment_Amount    290
Loan_Tenure_Months          290
Loan_Type                   290
Outstanding_Loan_Balance    289
Loan_Repayment_Status       288
Loan_Start_Date             288
Referral_Source             252
Last_Login_Date             169
Full_Name                     8
KYC_Status                    7
Monthly_Deposit_Avg           6
Savings_Balance               6
Has_Loan                      5
Customer_Segment              5
District                      5
dtype: int64

In [10]:
# Duplicate Rows
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 3

In [11]:
# Duplicate Customer ID
duplicate_customers = df[df['Customer_ID'].duplicated(keep=False)]

duplicate_customers.sort_values(by='Customer_ID')

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
10,FSL-0011,Joshua Mitchell,862063426V,Male,1986-07-25,37,Kurunegala,North Western,Urban,Regular,2023-12-05,0.1,778313.09,17429.30,8970.61,8458.69,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-22,28,Branch,No,Verified,2020-11-28,No,No,No,NaN,Yes,No,2,Referral,NaN,Ignored,No
500,FSL-0011,Joshua Mitchell,862063426V,Male,1986-07-25,37,Kurunegala,North Western,Urban,Regular,2023-12-05,0.1,778313.09,17429.30,8970.61,8458.69,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-22,28,Branch,No,Verified,2020-11-28,No,No,No,NaN,Yes,No,2,Referral,NaN,Ignored,No
45,FSL-0046,Nicole Morris,012378685V,Male,2001-08-25,22,Ratnapura,Sabaragamuwa,Suburban,Starter,2015-03-19,8.8,42108.97,2951.75,1857.48,1094.27,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-13,17,Online,Yes,Verified,2023-08-01,No,No,Yes,1819779.08,No,Yes,3,Branch,NaN,Responded,No
501,FSL-0046,Nicole Morris,012378685V,Male,2001-08-25,22,Ratnapura,Sabaragamuwa,Suburban,Starter,2015-03-19,8.8,42108.97,2951.75,1857.48,1094.27,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-13,17,Online,Yes,Verified,2023-08-01,No,No,Yes,1819779.08,No,Yes,3,Branch,NaN,Responded,No
88,FSL-0089,Catherine Mitchell,821642369V,Male,1890-03-11,134,Matara,Southern,Urban,Starter,2016-09-28,7.3,82776.58,3596.14,2447.45,1148.69,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-11-26,29,Branch,Yes,Verified,2022-06-08,No,No,Yes,1365551.20,No,Yes,3,Digital,NaN,Responded,Yes
502,FSL-0089,Catherine Mitchell,821642369V,Male,1982-06-13,41,Matara,Southern,Urban,Starter,2016-09-28,7.3,82776.58,3596.14,2447.45,1148.69,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-11-26,29,Branch,Yes,Verified,2022-06-08,No,No,Yes,1365551.20,No,Yes,3,Digital,NaN,Responded,Yes
130,FSL-0131,Ryan Torres,992664913V,Male,1999-09-23,24,Trincomalee,Eastern,Suburban,Regular,2016-07-28,7.4,368051.95,11317.12,9837.15,1479.97,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,3,Online,Yes,NaN,2021-04-19,No,No,Yes,492870.74,No,Yes,3,Agent,NaN,Unsubscribed,Yes
503,FSL-0131,Ryan Torres,992664913V,Male,1999-09-23,24,Trincomalee,Eastern,Suburban,Regular,2016-07-28,7.4,368051.95,11317.12,9837.15,1479.97,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,3,Online,Yes,Pending,2021-04-19,No,No,Yes,492870.74,No,Yes,3,Agent,NaN,Unsubscribed,Yes
200,FSL-0201,Nancy Johnson,821599078V,Male,1982-06-08,41,Gampaha,Western,Suburban,Regular,2020-05-22,3.6,461148.18,33249.13,22502.93,10746.20,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2025-08-20,3,Online,Yes,Verified,2021-10-16,No,No,No,NaN,Yes,Yes,3,Referral,Friend,Responded,No
504,FSL-0201,Nancy Johnson,821599078V,Male,1982-06-08,41,Gampaha,Western,Suburban,Regular,2020-05-22,3.6,461148.18,33249.13,22502.93,10746.20,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-10,3,Online,Yes,Verified,2021-10-16,No,No,No,NaN,Yes,Yes,3,Referral,Friend,Responded,No
280,FSL-0281,Linda Scott,916433090V,Female,1991-05-23,32,Matara,Southern,Urban,Regular,2016-09-28,7.3,532899.09,15219.71,9748.78,5470.93,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-09-03,17,Agent,No,Verified,2021-12-25,No,No,Yes,912753.66,No,No,2,Branch,Colleague,Ignored,Yes
505,FSL-0281,Linda Scott,916433090V,Female,1991-05-23,32,Matara,Southern,Urban,Regular,2016-09-28,7.3,532899.09,15219.71,9748.78,5470.93,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-09-03,17,Agent,No,Verified,2021-12-25,No,No,Yes,912753.66,No,No,2,Branch,Colleague,Ignored,Yes
350,FSL-0351,Charles Morgan,850611344V,Female,1971-09-21,52,Gampaha,Western,Rural,Regular,2018-07-24,5.4,168510.97,9013.69,7234.22,1779.47,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-02,10,Agent,No,Verified,2021-02-04,No,No,No,NaN,No,Yes,2,Branch,NaN,Unsubscribed,No
506,FSL-0351,Charles Morgan,717648100V,Female,1971-09-21,52,Gampaha,Western,Rural,Regular,2018-07-24,5.4,168510.97,9013.69,7234.22,1779.47,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-02,10,Agent,No,Verified,2021-02-04,No,No,No,NaN,No,Yes,2,Branch,NaN,Unsubscribed,No
420,FSL-0421,Nicole Roberts,918354937V,Female,1982-09-02,41,Ratnapura,Sabaragamuwa,Rural,Regular,2020-07-02,3.5,497834.63,20266.24,18093.43,2172.81,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-16,25,Branch,Yes,Verified,2020-12-23,No,No,Yes,404601.63,No,Yes,3,Referral,Family,Responded,No
507,FSL-0421,Nicole Roberts,827457336V,Female,1982-09-02,41,Ratnapura,Sabaragamuwa,Rural,Regular,2020-07-02,3.5,497834.63,20266.24,18093.43,2172.81,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-16,25,Branch,Yes,Verified,2020-12-23,No,No,Yes,404601.63,No,Yes,3,Referral,Family,Responded,No

In [12]:
# Check Invalid ages
invalid_age = df[(df['Age'] < 18) | (df['Age'] > 100)]

print("Invalid Age Records:", len(invalid_age))

Invalid Age Records: 3

In [13]:
# Negative savings balances
negative_savings = df[df['Savings_Balance'] < 0]

print("Negative Savings Records:", len(negative_savings))

Negative Savings Records: 4

## Data Quality
we get some real World dataset have some issues missing, duplicate, formatting problam, we want slove all those after ww can get good improve.

In [14]:
# Store original row count
original_rows = df.shape[0]

# Remove exact duplicate rows
df = df.drop_duplicates()

# New row count
new_rows = df.shape[0]

print("Original Rows:", original_rows)
print("Rows After Removing Exact Duplicates:", new_rows)
print("Duplicates Removed:", original_rows - new_rows)

Original Rows: 508
Rows After Removing Exact Duplicates: 505
Duplicates Removed: 3

In [15]:
# Find duplicate customer IDs
duplicate_customers = df[df['Customer_ID'].duplicated(keep=False)]

# Display duplicates
duplicate_customers.sort_values(by='Customer_ID')

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
88,FSL-0089,Catherine Mitchell,821642369V,Male,1890-03-11,134,Matara,Southern,Urban,Starter,2016-09-28,7.3,82776.58,3596.14,2447.45,1148.69,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-11-26,29,Branch,Yes,Verified,2022-06-08,No,No,Yes,1365551.20,No,Yes,3,Digital,NaN,Responded,Yes
502,FSL-0089,Catherine Mitchell,821642369V,Male,1982-06-13,41,Matara,Southern,Urban,Starter,2016-09-28,7.3,82776.58,3596.14,2447.45,1148.69,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-11-26,29,Branch,Yes,Verified,2022-06-08,No,No,Yes,1365551.20,No,Yes,3,Digital,NaN,Responded,Yes
130,FSL-0131,Ryan Torres,992664913V,Male,1999-09-23,24,Trincomalee,Eastern,Suburban,Regular,2016-07-28,7.4,368051.95,11317.12,9837.15,1479.97,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,3,Online,Yes,NaN,2021-04-19,No,No,Yes,492870.74,No,Yes,3,Agent,NaN,Unsubscribed,Yes
503,FSL-0131,Ryan Torres,992664913V,Male,1999-09-23,24,Trincomalee,Eastern,Suburban,Regular,2016-07-28,7.4,368051.95,11317.12,9837.15,1479.97,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,3,Online,Yes,Pending,2021-04-19,No,No,Yes,492870.74,No,Yes,3,Agent,NaN,Unsubscribed,Yes
200,FSL-0201,Nancy Johnson,821599078V,Male,1982-06-08,41,Gampaha,Western,Suburban,Regular,2020-05-22,3.6,461148.18,33249.13,22502.93,10746.20,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2025-08-20,3,Online,Yes,Verified,2021-10-16,No,No,No,NaN,Yes,Yes,3,Referral,Friend,Responded,No
504,FSL-0201,Nancy Johnson,821599078V,Male,1982-06-08,41,Gampaha,Western,Suburban,Regular,2020-05-22,3.6,461148.18,33249.13,22502.93,10746.20,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-10,3,Online,Yes,Verified,2021-10-16,No,No,No,NaN,Yes,Yes,3,Referral,Friend,Responded,No
350,FSL-0351,Charles Morgan,850611344V,Female,1971-09-21,52,Gampaha,Western,Rural,Regular,2018-07-24,5.4,168510.97,9013.69,7234.22,1779.47,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-02,10,Agent,No,Verified,2021-02-04,No,No,No,NaN,No,Yes,2,Branch,NaN,Unsubscribed,No
506,FSL-0351,Charles Morgan,717648100V,Female,1971-09-21,52,Gampaha,Western,Rural,Regular,2018-07-24,5.4,168510.97,9013.69,7234.22,1779.47,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-08-02,10,Agent,No,Verified,2021-02-04,No,No,No,NaN,No,Yes,2,Branch,NaN,Unsubscribed,No
420,FSL-0421,Nicole Roberts,918354937V,Female,1982-09-02,41,Ratnapura,Sabaragamuwa,Rural,Regular,2020-07-02,3.5,497834.63,20266.24,18093.43,2172.81,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-16,25,Branch,Yes,Verified,2020-12-23,No,No,Yes,404601.63,No,Yes,3,Referral,Family,Responded,No
507,FSL-0421,Nicole Roberts,827457336V,Female,1982-09-02,41,Ratnapura,Sabaragamuwa,Rural,Regular,2020-07-02,3.5,497834.63,20266.24,18093.43,2172.81,Active,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-16,25,Branch,Yes,Verified,2020-12-23,No,No,Yes,404601.63,No,Yes,3,Referral,Family,Responded,No

In [16]:
# Columns likely containing Yes/No values
binary_columns = [
    'Mobile_App_User',
    'Has_Loan',
    'Has_Fixed_Deposit',
    'Has_Insurance'
]

# Standardize Yes/No formatting
for col in binary_columns:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

print("Binary columns standardized")

Binary columns standardized

In [17]:
# Standardize Province names
df['Province'] = df['Province'].astype(str).str.strip().str.title()

# Standardize District names
df['District'] = df['District'].astype(str).str.strip().str.title()

print("Province and District names standardized")

Province and District names standardized

In [ ]:
# Invalid age records
invalid_age = df[(df['Age'] < 18) | (df['Age'] > 100)]

invalid_age[['Customer_ID', 'Age']]

    Customer_ID  Age
33     FSL-0034    4
88     FSL-0089  134
270    FSL-0271  150

Impossible age values were replaced useing madian valied age

In [ ]:
# Calculate median age
median_age = df[(df['Age'] >= 18) & (df['Age'] <= 100)]['Age'].median()

# Replace invalid ages with median
df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = median_age

print("Invalid ages replaced with median age:", median_age)

Invalid ages replaced with median age: 36.5

/tmp/ipykernel_5399/1942311139.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '36.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = median_age

In [ ]:
# Negative savings balances
negative_savings = df[df['Savings_Balance'] < 0]

negative_savings[['Customer_ID', 'Savings_Balance']]

    Customer_ID  Savings_Balance
22     FSL-0023         -45000.0
99     FSL-0100         -12500.0
175    FSL-0176         -88000.0
320    FSL-0321          -5000.0

In [ ]:
# Replace negative savings with NaN
df.loc[df['Savings_Balance'] < 0, 'Savings_Balance'] = np.nan

print("Negative savings balances converted to missing values")

Negative savings balances converted to missing values

In [ ]:
# Fill missing savings balance with median
median_savings = df['Savings_Balance'].median()

df['Savings_Balance'] = df['Savings_Balance'].fillna(median_savings)

print("Missing savings balances filled with median:", median_savings)

Missing savings balances filled with median: 448297.06

In [ ]:
# Missing values after cleaning
missing_after = df.isnull().sum()

missing_after[missing_after > 0].sort_values(ascending=False)

FD_Amount                   358
Loan_Amount                 291
Monthly_Repayment_Amount    290
Loan_Tenure_Months          290
Loan_Type                   290
Outstanding_Loan_Balance    289
Loan_Repayment_Status       288
Loan_Start_Date             288
Referral_Source             252
Last_Login_Date             169
Full_Name                     8
KYC_Status                    7
Monthly_Deposit_Avg           6
Savings_Balance               6
Has_Loan                      5
Customer_Segment              5
District                      5
dtype: int64

In [ ]:
# Save cleaned dataset
df.to_excel("FinSight_Cleaned_Data.xlsx", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [ ]:
# Stage 1 - Setup

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

print("Setup completed successfully")

Setup completed successfully

In [ ]:
df = pd.read_excel("/content/20260512_FintechTrainee_CaseStudy_Dataset_FinSightLanka_F.xlsx")

df.head()

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
0,FSL-0001,Mark Johnson,808614657V,Female,1980-12-26,43,Kandy,Central,Suburban,Regular,2021-02-11,2.9,87812.29,3979.24,1264.91,2714.33,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-07-21,28,Branch,Yes,Verified,2020-01-14,No,No,No,NaN,No,Yes,2,Referral,Friend,Responded,Yes
1,FSL-0002,Deborah Phillips,718478527V,Female,1971-12-13,52,Badulla,Uva,Urban,Starter,2015-11-19,8.1,85045.89,5933.17,3981.82,1951.35,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,0,Branch,No,Expired,2021-04-21,No,No,No,NaN,No,Yes,2,Referral,Family,Ignored,No
2,FSL-0003,Charles Phillips,933515010V,Male,1993-12-17,30,Kandy,Central,Suburban,Regular,2022-03-06,1.8,556766.33,18471.79,9135.59,9336.20,Inactive,Silver,Yes,Personal,2424885.11,48.0,55570.28,On-Time,2022-10-08,2124601.17,Yes,2023-12-01,22,Branch,No,Verified,2023-08-09,No,No,Yes,1166599.45,No,No,3,Agent,Colleague,Responded,No
3,FSL-0004,Rachel Hall,720422796V,Male,1972-02-11,51,Kandy,Central,Suburban,Regular,2019-09-26,4.3,485199.04,20905.30,13745.93,7159.37,Active,Silver,Yes,Personal,2056836.06,12.0,188543.31,Delayed,2022-09-29,1518451.26,No,NaT,2,App,Yes,Verified,2020-01-07,No,No,Yes,1051113.61,Yes,No,4,Referral,NaN,Ignored,Yes
4,FSL-0005,Sharon Bell,940729689V,Male,1994-03-13,29,Colombo,Western,Suburban,Regular,2016-04-03,7.8,744696.92,54156.83,43271.27,10885.56,Active,Silver,Yes,Personal,302677.68,48.0,6936.36,Delayed,2022-03-24,227298.61,Yes,2023-09-30,12,Online,Yes,Verified,2021-03-09,No,No,No,NaN,No,Yes,3,Referral,NaN,Unsubscribed,No

In [ ]:
df.shape

(508, 44)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer_ID                508 non-null    object
 1   Full_Name                  500 non-null    object
 2   NIC_Number                 508 non-null    object
 3   Gender                     508 non-null    object
 4   Date_of_Birth              508 non-null    datetime64[ns]
 5   Age                        508 non-null    int64
 6   District                   503 non-null    object
 7   Province                   508 non-null    object
 8   Urban_Rural                508 non-null    object
 9   Customer_Segment           503 non-null    object
 10  Account_Open_Date          508 non-null    datetime64[ns]
 11  Customer_Tenure_Years      508 non-null    float64
 12  Savings_Balance            502 non-null    float64
 13  Monthly_Deposit_Avg        502 non-null    float64
 14  Monthly_Withdrawal_Avg     508 non-null    float64
 15  Net_Monthly_Flow           508 non-null    float64
 16  Account_Status             508 non-null    object
 17  Interest_Rate_Tier         508 non-null    object
 18  Has_Loan                   503 non-null    object
 19  Loan_Type                  218 non-null    object
 20  Loan_Amount                217 non-null    float64
 21  Loan_Tenure_Months         218 non-null    float64
 22  Monthly_Repayment_Amount   218 non-null    float64
 23  Loan_Repayment_Status      220 non-null    object
 24  Loan_Start_Date            220 non-null    datetime64[ns]
 25  Outstanding_Loan_Balance   219 non-null    float64
 26  Mobile_App_User            508 non-null    object
 27  Last_Login_Date            339 non-null    datetime64[ns]
 28  Monthly_Transaction_Count  508 non-null    int64
 29  Preferred_Channel          508 non-null    object
 30  Push_Notification_Enabled  508 non-null    object
 31  KYC_Status                 501 non-null    object
 32  KYC_Last_Updated           508 non-null    datetime64[ns]
 33  Suspicious_Activity_Flag   508 non-null    object
 34  PEP_Flag                   508 non-null    object
 35  Has_Fixed_Deposit          508 non-null    object
 36  FD_Amount                  150 non-null    float64
 37  Has_Insurance              508 non-null    object
 38  Has_Mobile_Wallet          508 non-null    object
 39  Number_of_Products         508 non-null    int64
 40  Acquisition_Channel        508 non-null    object
 41  Referral_Source            256 non-null    object
 42  Last_Campaign_Response     508 non-null    object
 43  Promo_Code_Used            508 non-null    object
dtypes: datetime64[ns](5), float64(10), int64(3), object(26)
memory usage: 174.8+ KB

Q1

In [ ]:
df.groupby("Customer_Segment")["Savings_Balance"].mean().sort_values(ascending=False)

Customer_Segment
Regular    3.605493e+06
Premium    2.626478e+06
Starter    8.123682e+04
Name: Savings_Balance, dtype: float64

In [ ]:
df.groupby("Province")["Savings_Balance"].mean().sort_values(ascending=False)

Province
North Western    1.828931e+07
Eastern          9.531040e+05
Sabaragamuwa     8.844542e+05
Western          8.426941e+05
Central          7.494964e+05
Southern         6.467234e+05
Uva              6.306385e+05
Northern         6.169215e+05
Name: Savings_Balance, dtype: float64

In [ ]:
df.groupby("Urban_Rural")["Savings_Balance"].mean().sort_values(ascending=False)

Urban_Rural
Urban       6.205574e+06
Rural       7.150404e+05
Suburban    6.621971e+05
Name: Savings_Balance, dtype: float64

In [ ]:
bins = [0,25,35,50,65,120]

labels = ["<25","26-35","36-50","51-65","65+"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

df.groupby("Age_Group")["Savings_Balance"].sum().sort_values(ascending=False)

/tmp/ipykernel_5399/646807019.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age_Group")["Savings_Balance"].sum().sort_values(ascending=False)

Age_Group
<25      1.065775e+09
36-50    1.728747e+08
26-35    1.173475e+08
51-65    2.423040e+07
65+      6.400158e+04
Name: Savings_Balance, dtype: float64

In [ ]:
[c for c in df.columns if "saving" in c.lower()]

['Savings_Balance']

## Assumption for Savings Growth Analysis
dataset does not contain monthly transaction history or month-over-month savings changes

In [ ]:
# Calculate median savings balance
median_savings = df["Savings_Balance"].median()

# Classify customers
df["Savings_Status"] = np.where(
    df["Savings_Balance"] >= median_savings,
    "Growing Savings",
    "Draining/Stagnating"
)

# Percentage calculation
savings_status = df["Savings_Status"].value_counts(normalize=True) * 100

savings_status

Savings_Status
Draining/Stagnating    50.590551
Growing Savings        49.409449
Name: proportion, dtype: float64

In [ ]:
[c for c in df.columns if "loan" in c.lower()]

['Has_Loan',
 'Loan_Type',
 'Loan_Amount',
 'Loan_Tenure_Months',
 'Loan_Repayment_Status',
 'Loan_Start_Date',
 'Outstanding_Loan_Balance']

In [ ]:
df["Has_Loan"].value_counts()

Has_Loan
No     285
Yes    218
Name: count, dtype: int64

In [ ]:
loan_penetration = (
    (df["Has_Loan"] == "Yes").sum()
    / len(df)
) * 100

print("Loan Penetration Rate:", round(loan_penetration,2), "%")

Loan Penetration Rate: 42.91 %

In [ ]:
df.groupby("Customer_Segment")["Has_Loan"] \
.apply(lambda x: (x == "Yes").mean() * 100) \
.sort_values(ascending=False)

Customer_Segment
Premium    45.054945
Regular    43.887147
Starter    37.634409
Name: Has_Loan, dtype: float64

In [ ]:
[c for c in df.columns if "channel" in c.lower()]

['Preferred_Channel', 'Acquisition_Channel']

In [ ]:
df.groupby("Acquisition_Channel")["Has_Loan"] \
.apply(lambda x: (x == "Yes").mean() * 100) \
.sort_values(ascending=False)

Acquisition_Channel
Agent       47.457627
Referral    43.181818
Digital     40.909091
Branch      40.476190
Name: Has_Loan, dtype: float64

In [ ]:
# Only customers with loans
loan_customers = df[df["Has_Loan"] == "Yes"].copy()

# Create ratio
loan_customers["Debt_to_Savings_Ratio"] = (
    loan_customers["Outstanding_Loan_Balance"]
    / loan_customers["Savings_Balance"]
)

loan_customers[[
    "Customer_ID",
    "Debt_to_Savings_Ratio"
]].head()

  Customer_ID  Debt_to_Savings_Ratio
2    FSL-0003               3.815966
3    FSL-0004               3.129543
4    FSL-0005               0.305223
6    FSL-0007               0.811398
9    FSL-0010               2.589056

Q2

In [ ]:
high_risk = loan_customers[
    loan_customers["Debt_to_Savings_Ratio"] > 1
]

print("High Risk Customers:", len(high_risk))

print(
    "Total Exposure:",
    high_risk["Outstanding_Loan_Balance"].sum()
)

High Risk Customers: 126
Total Exposure: 130101268.26

In [ ]:
df["Loan_Repayment_Status"].value_counts()

Loan_Repayment_Status
On-Time      133
Delayed       64
Defaulted     23
Name: count, dtype: int64

In [ ]:
default_rate = (
    (df["Loan_Repayment_Status"] == "Defaulted").sum()
    / len(df[df["Has_Loan"] == "Yes"])
) * 100

print("Default Rate:", round(default_rate,2), "%")

Default Rate: 10.55 %

In [ ]:
df.groupby("Customer_Segment")["Loan_Repayment_Status"] \
.apply(lambda x: (x == "Defaulted").mean() * 100) \
.sort_values(ascending=False)

Customer_Segment
Starter    7.526882
Premium    4.395604
Regular    3.761755
Name: Loan_Repayment_Status, dtype: float64

In [ ]:
df.groupby("District")["Loan_Repayment_Status"] \
.apply(lambda x: (x == "Defaulted").mean() * 100) \
.sort_values(ascending=False)

District
Colombo        8.163265
Ratnapura      7.142857
Kurunegala     7.142857
Gampaha        5.555556
Matara         4.347826
Kandy          4.347826
Galle          2.941176
Trincomalee    2.000000
Badulla        2.000000
Jaffna         1.724138
Columbo        0.000000
Gale           0.000000
Kanady         0.000000
Jafna          0.000000
Name: Loan_Repayment_Status, dtype: float64

In [ ]:
df.groupby("Loan_Type")["Loan_Repayment_Status"] \
.apply(lambda x: (x == "Defaulted").mean() * 100) \
.sort_values(ascending=False)

Loan_Type
Vehicle     15.686275
Housing     11.320755
Personal     7.272727
Business     6.779661
Name: Loan_Repayment_Status, dtype: float64

Q3

In [ ]:
df["Mobile_App_User"].value_counts()

Mobile_App_User
Yes    339
No     169
Name: count, dtype: int64

In [ ]:
df.groupby("Mobile_App_User")["Savings_Balance"] \
.mean() \
.sort_values(ascending=False)

Mobile_App_User
Yes    3.742537e+06
No     7.804942e+05
Name: Savings_Balance, dtype: float64

In [ ]:
df["Has_Fixed_Deposit"].value_counts()

Has_Fixed_Deposit
No     358
Yes    150
Name: count, dtype: int64

In [ ]:
df["Has_Insurance"].value_counts()

Has_Insurance
No     375
Yes    133
Name: count, dtype: int64

In [ ]:
cross_sell = df[
    (df["Savings_Balance"] > 0) &
    (df["Has_Fixed_Deposit"] == "No") &
    (df["Has_Insurance"] == "No")
]

cross_sell.head()

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,Account_Open_Date,Customer_Tenure_Years,Savings_Balance,Monthly_Deposit_Avg,Monthly_Withdrawal_Avg,Net_Monthly_Flow,Account_Status,Interest_Rate_Tier,Has_Loan,Loan_Type,Loan_Amount,Loan_Tenure_Months,Monthly_Repayment_Amount,Loan_Repayment_Status,Loan_Start_Date,Outstanding_Loan_Balance,Mobile_App_User,Last_Login_Date,Monthly_Transaction_Count,Preferred_Channel,Push_Notification_Enabled,KYC_Status,KYC_Last_Updated,Suspicious_Activity_Flag,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used,Age_Group,Savings_Status
0,FSL-0001,Mark Johnson,808614657V,Female,1980-12-26,43,Kandy,Central,Suburban,Regular,2021-02-11,2.9,87812.29,3979.24,1264.91,2714.33,Active,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-07-21,28,Branch,Yes,Verified,2020-01-14,No,No,No,NaN,No,Yes,2,Referral,Friend,Responded,Yes,36-50,Draining/Stagnating
1,FSL-0002,Deborah Phillips,718478527V,Female,1971-12-13,52,Badulla,Uva,Urban,Starter,2015-11-19,8.1,85045.89,5933.17,3981.82,1951.35,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,No,NaT,0,Branch,No,Expired,2021-04-21,No,No,No,NaN,No,Yes,2,Referral,Family,Ignored,No,51-65,Draining/Stagnating
4,FSL-0005,Sharon Bell,940729689V,Male,1994-03-13,29,Colombo,Western,Suburban,Regular,2016-04-03,7.8,744696.92,54156.83,43271.27,10885.56,Active,Silver,Yes,Personal,302677.68,48.0,6936.36,Delayed,2022-03-24,227298.61,Yes,2023-09-30,12,Online,Yes,Verified,2021-03-09,No,No,No,NaN,No,Yes,3,Referral,NaN,Unsubscribed,No,26-35,Growing Savings
5,FSL-0006,Nancy Harris,850611344V,Male,1985-03-02,38,Trincomalee,Eastern,Suburban,Regular,2015-01-30,8.9,75374.61,4361.64,1907.63,2454.01,Inactive,Standard,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-07-31,19,Agent,Yes,Verified,2023-03-15,No,No,No,NaN,No,Yes,2,Agent,Colleague,Ignored,No,36-50,Draining/Stagnating
7,FSL-0008,Samantha Anderson,831144566V,Male,1983-04-24,40,Colombo,Western,Suburban,Regular,2023-05-22,0.6,264611.75,6088.33,3568.21,2520.12,Inactive,Silver,No,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,2023-10-09,7,Branch,Yes,Verified,2021-04-26,No,No,No,NaN,No,Yes,2,Digital,NaN,Ignored,No,36-50,Draining/Stagnating

In [ ]:
print("Cross-Sell Customer Count:", len(cross_sell))

print(
    "Total Savings Value:",
    cross_sell["Savings_Balance"].sum()
)

Cross-Sell Customer Count: 252
Total Savings Value: 222553782.55

In [ ]:
[c for c in df.columns if "channel" in c.lower()]

['Preferred_Channel', 'Acquisition_Channel']

In [ ]:
df.groupby("Acquisition_Channel")["Savings_Balance"] \
.mean() \
.sort_values(ascending=False)

Acquisition_Channel
Digital     8.387737e+06
Branch      8.133348e+05
Referral    7.586037e+05
Agent       6.435079e+05
Name: Savings_Balance, dtype: float64

In [ ]:
df.groupby("Acquisition_Channel")["Loan_Repayment_Status"] \
.apply(lambda x: (x == "Defaulted").mean() * 100) \
.sort_values()

Acquisition_Channel
Agent       2.542373
Branch      4.761905
Digital     5.303030
Referral    5.303030
Name: Loan_Repayment_Status, dtype: float64

In [ ]:
df.to_excel("FinSight_Cleaned_Data.xlsx", index=False)

In [ ]:
from google.colab import files
files.download("FinSight_Cleaned_Data.xlsx")